// <auto-generated />
namespace LearnerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_added_banner_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_added_banner_status));
        
        string IMigrationMetadata.Id
        {
            get { return "202509050920067_mig_added_banner_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
