// <auto-generated />
namespace LearnerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_teacher_and_course_relationship_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_teacher_and_course_relationship_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202509051154516_mig_teacher_and_course_relationship_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
